defmodule ThistleTea.Game.Core.Entity.Component.Internal do
  @moduledoc """
  Server-only entity state that is never sent to the client: world/area, AI and
  combat bookkeeping, pending events, and casting state. Entity-kind concerns
  live in sub-structs — `Internal.Creature` (creature-template config),
  `Internal.Spawn` (mob spawn/respawn), `Internal.Loot` (mob loot/corpse
  phase), and `Internal.Summon` (summoned game objects) — which stay nil on
  entities they don't apply to.
  """
  alias ThistleTea.Game.Core.Chat.ChatStatus
  alias ThistleTea.Game.Core.Combat.DamageOrigin
  alias ThistleTea.Game.Core.Death.CorpseReclaim
  alias ThistleTea.Game.Core.Entity.Component.Internal.ObjectAction
  alias ThistleTea.Game.Core.Entity.Component.Internal.Scripts
  alias ThistleTea.Game.Core.Honor.Damage, as: HonorDamage
  alias ThistleTea.Game.Core.Pet.Companion
  alias ThistleTea.Game.Core.Pet.PetStable
  alias ThistleTea.Game.Core.Player.PlayedTime
  alias ThistleTea.Game.Core.Player.TalentReset
  alias ThistleTea.Game.Core.Pvp
  alias ThistleTea.Game.Core.Vendor.Buyback
  alias ThistleTea.Game.Core.WorldRef

  defstruct [
    :home_bind,
    :name,
    :area,
    :outdoors?,
    :liquid_spell_id,
    :spells,
    :spellbook,
    :casting,
    :channel_game_object_guid,
    :channel_game_object_owned?,
    :next_swing_spell,
    :creature,
    :corpse,
    :spawn,
    :loot,
    :item_loot,
    :summon,
    :pet,
    :possession,
    :movement_handoff,
    :mini_pet,
    :guardian,
    :chair,
    :goober,
    :trap,
    :ritual,
    :totem,
    :duel,
    :auto_shot,
    :ranged_attack_at,
    :fishing,
    :gathering,
    :taxi_flight,
    :event,
    :in_combat,
    :threat,
    :threat_refs,
    :last_hostile_time,
    :combat_timer_target,
    :combat_leash,
    :combat_zone,
    :companion_monitor,
    :last_trade_id,
    :item_logout_at,
    :last_auction_id,
    :last_vendor_purchase_id,
    :last_mana_use_at,
    :next_sober_at,
    :health_regen_carry,
    :running,
    :behavior_tree,
    :blackboard,
    :ai_tick_ref,
    :ai_tick_token,
    :visibility_cell,
    :proximity,
    :proximity_refresh,
    :hidden_cell,
    :movement_start_time,
    :movement_start_position,
    :safe_position,
    :movement_speed,
    :movement_options,
    :charge,
    :fall,
    :breath,
    :fatigue,
    :lava_exposure,
    :pending_resurrect,
    :pending_summon,
    :killed_by,
    :pve_reward_eligible?,
    :rest_type,
    :rest_started_at,
    :rest_logout_at,
    :logout,
    :defense_window,
    :hunter_parry_window,
    :combo_expires_at,
    :combo_target_guid,
    :undetectable_until,
    :invincibility_health_threshold,
    world: WorldRef.open(0),
    proximity_checks: %{},
    single_target_sequence: 0,
    scripts: %Scripts{},
    object_action: %ObjectAction{},
    buyback: %Buyback{},
    chat_status: %ChatStatus{},
    temporary_threat: %{},
    diminishing_returns: %{},
    companion: Companion.none(),
    corpse_reclaim: %CorpseReclaim{},
    guardians: %{},
    guardian_monitors: %{},
    game_object_monitors: %{},
    pet_stable: %PetStable{},
    pvp: %Pvp{},
    honor_damage: %HonorDamage{},
    damage_origin: %DamageOrigin{},
    talent_reset: %TalentReset{},
    played: %PlayedTime{},
    forgotten_skills: %{},
    rest_bonus: 0.0,
    mailbox: [],
    starting_items: [],
    action_buttons: %{},
    totem_guids: %{},
    cooldowns: %{},
    events: [],
    navigation_intents: [],
    broadcast_update?: false,
    death_finalized?: false,
    rooted?: false,
    spline_id: 0,
    godmode: false,
    combat_timeout_ms: 5_000
  ]
end
