defmodule ThistleTea.DB.Mangos.CreatureTemplate do
  use Ecto.Schema

  alias ThistleTea.DB.Mangos

  @primary_key {:entry, :integer, autogenerate: false}
  schema "creature_template" do
    field(:name, :string)
    field(:sub_name, :string, source: :subname)
    field(:min_level, :integer, source: :level_min, default: 1)
    field(:max_level, :integer, source: :level_max, default: 1)
    field(:model_id1, :integer, source: :display_id1, default: 0)
    field(:model_id2, :integer, source: :display_id2, default: 0)
    field(:model_id3, :integer, source: :display_id3, default: 0)
    field(:model_id4, :integer, source: :display_id4, default: 0)
    field(:display_scale1, :float, default: 0.0)
    field(:display_scale2, :float, default: 0.0)
    field(:display_scale3, :float, default: 0.0)
    field(:display_scale4, :float, default: 0.0)
    field(:display_probability1, :integer, default: 0)
    field(:display_probability2, :integer, default: 0)
    field(:display_probability3, :integer, default: 0)
    field(:display_probability4, :integer, default: 0)
    field(:display_total_probability, :integer, default: 0)
    field(:faction_alliance, :integer, source: :faction, default: 0)
    field(:faction_horde, :integer, virtual: true, default: 0)
    field(:scale, :float, virtual: true)
    field(:family, :integer, source: :pet_family, default: 0)
    field(:creature_type, :integer, source: :type, default: 0)
    field(:inhabit_type, :integer, default: 3)
    field(:regenerate_stats, :integer, virtual: true)
    field(:racial_leader, :integer, default: 0)
    field(:npc_flags, :integer, default: 0)
    field(:unit_flags, :integer, virtual: true, default: 0)
    field(:dynamic_flags, :integer, virtual: true, default: 0)
    field(:extra_flags, :integer, source: :flags_extra, default: 0)
    field(:creature_type_flags, :integer, source: :static_flags1, default: 0)
    field(:speed_walk, :float, default: 1.0)
    field(:speed_run, :float, default: 1.14286)
    field(:detection_range, :float, default: 18.0)
    field(:call_for_help_range, :float, default: 5.0)
    field(:leash_range, :float, default: 0.0)
    field(:unit_class, :integer, default: 0)
    field(:rank, :integer, default: 0)
    field(:health_multiplier, :float, default: 1.0)
    field(:mana_multiplier, :float, default: 1.0)
    field(:power_multiplier, :float, virtual: true, default: 1.0)
    field(:damage_multiplier, :float, default: 1.0)
    field(:damage_variance, :float, default: 0.14)
    field(:armor_multiplier, :float, default: 1.0)
    field(:experience_multiplier, :float, source: :xp_multiplier, default: 1.0)
    field(:min_level_health, :integer, virtual: true, default: 0)
    field(:max_level_health, :integer, virtual: true, default: 0)
    field(:min_level_mana, :integer, virtual: true, default: 0)
    field(:max_level_mana, :integer, virtual: true, default: 0)
    field(:min_melee_dmg, :float, virtual: true, default: 0.0)
    field(:max_melee_dmg, :float, virtual: true, default: 0.0)
    field(:min_ranged_dmg, :float, virtual: true, default: 0.0)
    field(:max_ranged_dmg, :float, virtual: true, default: 0.0)
    field(:armor, :integer, virtual: true, default: 0)
    field(:melee_attack_power, :integer, virtual: true, default: 0)
    field(:ranged_attack_power, :integer, virtual: true, default: 0)
    field(:melee_base_attack_time, :integer, source: :base_attack_time, default: 2000)
    field(:ranged_base_attack_time, :integer, source: :ranged_attack_time, default: 2000)
    field(:damage_school, :integer, default: 0)
    field(:min_loot_gold, :integer, source: :gold_min, default: 0)
    field(:max_loot_gold, :integer, source: :gold_max, default: 0)
    field(:loot_id, :integer, default: 0)
    field(:pickpocket_loot_id, :integer, default: 0)
    field(:skinning_loot_id, :integer, default: 0)
    field(:kill_credit1, :integer, virtual: true, default: 0)
    field(:kill_credit2, :integer, virtual: true, default: 0)
    field(:mechanic_immune_mask, :integer, default: 0)
    field(:school_immune_mask, :integer, default: 0)
    field(:resistance_holy, :integer, source: :holy_res, default: 0)
    field(:resistance_fire, :integer, source: :fire_res, default: 0)
    field(:resistance_nature, :integer, source: :nature_res, default: 0)
    field(:resistance_frost, :integer, source: :frost_res, default: 0)
    field(:resistance_shadow, :integer, source: :shadow_res, default: 0)
    field(:resistance_arcane, :integer, source: :arcane_res, default: 0)
    field(:spell_id1, :integer, virtual: true, default: 0)
    field(:spell_id2, :integer, virtual: true, default: 0)
    field(:spell_id3, :integer, virtual: true, default: 0)
    field(:spell_id4, :integer, virtual: true, default: 0)
    field(:spell_list_id, :integer, default: 0)
    field(:pet_spell_data_id, :integer, source: :pet_spell_list_id, default: 0)
    field(:movement_type, :integer, default: 0)
    field(:trainer_type, :integer, default: 0)
    field(:trainer_spell, :integer, default: 0)
    field(:trainer_class, :integer, default: 0)
    field(:trainer_race, :integer, default: 0)
    field(:trainer_template_id, :integer, source: :trainer_id, default: 0)
    field(:vendor_template_id, :integer, source: :vendor_id, default: 0)
    field(:gossip_menu_id, :integer, default: 0)
    field(:equipment_template_id, :integer, source: :equipment_id, default: 0)
    field(:civilian, :integer, default: 0)
    field(:ai_name, :string, default: "")
    field(:auras, :string)

    has_many(:gossip_menu, Mangos.GossipMenu, foreign_key: :entry, references: :gossip_menu_id)
  end
end
