defmodule QuestTemplate do
  use Ecto.Schema

  @primary_key {:entry, :integer, autogenerate: false}
  schema "quest_template" do
    field(:method, :integer, source: :Method, default: 2)
    field(:zone_or_sort, :integer, source: :ZoneOrSort, default: 0)
    field(:min_level, :integer, source: :MinLevel, default: 0)
    field(:quest_level, :integer, source: :QuestLevel, default: 0)
    field(:type, :integer, source: :Type, default: 0)
    field(:required_classes, :integer, source: :RequiredClasses, default: 0)
    field(:required_races, :integer, source: :RequiredRaces, default: 0)
    field(:required_skill, :integer, source: :RequiredSkill, default: 0)
    field(:required_skill_value, :integer, source: :RequiredSkillValue, default: 0)
    field(:rep_objective_faction, :integer, source: :RepObjectiveFaction, default: 0)
    field(:rep_objective_value, :integer, source: :RepObjectiveValue, default: 0)
    field(:required_min_rep_faction, :integer, source: :RequiredMinRepFaction, default: 0)
    field(:required_min_rep_value, :integer, source: :RequiredMinRepValue, default: 0)
    field(:required_max_rep_faction, :integer, source: :RequiredMaxRepFaction, default: 0)
    field(:required_max_rep_value, :integer, source: :RequiredMaxRepValue, default: 0)
    field(:suggested_players, :integer, source: :SuggestedPlayers, default: 0)
    field(:limit_time, :integer, source: :LimitTime, default: 0)
    field(:quest_flags, :integer, source: :QuestFlags, default: 0)
    field(:special_flags, :integer, source: :SpecialFlags, default: 0)
    field(:prev_quest_id, :integer, source: :PrevQuestId, default: 0)
    field(:next_quest_id, :integer, source: :NextQuestId, default: 0)
    field(:exclusive_group, :integer, source: :ExclusiveGroup, default: 0)
    field(:next_quest_in_chain, :integer, source: :NextQuestInChain, default: 0)
    field(:src_item_id, :integer, source: :SrcItemId, default: 0)
    field(:src_item_count, :integer, source: :SrcItemCount, default: 0)
    field(:src_spell, :integer, source: :SrcSpell, default: 0)
    field(:title, :string, source: :Title)
    field(:details, :string, source: :Details)
    field(:objectives, :string, source: :Objectives)
    field(:offer_reward_text, :string, source: :OfferRewardText)
    field(:request_items_text, :string, source: :RequestItemsText)
    field(:end_text, :string, source: :EndText)
    field(:objective_text1, :string, source: :ObjectiveText1)
    field(:objective_text2, :string, source: :ObjectiveText2)
    field(:objective_text3, :string, source: :ObjectiveText3)
    field(:objective_text4, :string, source: :ObjectiveText4)
    field(:req_item_id1, :integer, source: :ReqItemId1, default: 0)
    field(:req_item_id2, :integer, source: :ReqItemId2, default: 0)
    field(:req_item_id3, :integer, source: :ReqItemId3, default: 0)
    field(:req_item_id4, :integer, source: :ReqItemId4, default: 0)
    field(:req_item_count1, :integer, source: :ReqItemCount1, default: 0)
    field(:req_item_count2, :integer, source: :ReqItemCount2, default: 0)
    field(:req_item_count3, :integer, source: :ReqItemCount3, default: 0)
    field(:req_item_count4, :integer, source: :ReqItemCount4, default: 0)
    field(:req_source_id1, :integer, source: :ReqSourceId1, default: 0)
    field(:req_source_id2, :integer, source: :ReqSourceId2, default: 0)
    field(:req_source_id3, :integer, source: :ReqSourceId3, default: 0)
    field(:req_source_id4, :integer, source: :ReqSourceId4, default: 0)
    field(:req_source_count1, :integer, source: :ReqSourceCount1, default: 0)
    field(:req_source_count2, :integer, source: :ReqSourceCount2, default: 0)
    field(:req_source_count3, :integer, source: :ReqSourceCount3, default: 0)
    field(:req_source_count4, :integer, source: :ReqSourceCount4, default: 0)
    field(:req_creature_or_go_id1, :integer, source: :ReqCreatureOrGOId1, default: 0)
    field(:req_creature_or_go_id2, :integer, source: :ReqCreatureOrGOId2, default: 0)
    field(:req_creature_or_go_id3, :integer, source: :ReqCreatureOrGOId3, default: 0)
    field(:req_creature_or_go_id4, :integer, source: :ReqCreatureOrGOId4, default: 0)
    field(:req_creature_or_go_count1, :integer, source: :ReqCreatureOrGOCount1, default: 0)
    field(:req_creature_or_go_count2, :integer, source: :ReqCreatureOrGOCount2, default: 0)
    field(:req_creature_or_go_count3, :integer, source: :ReqCreatureOrGOCount3, default: 0)
    field(:req_creature_or_go_count4, :integer, source: :ReqCreatureOrGOCount4, default: 0)
    field(:req_spell_cast1, :integer, source: :ReqSpellCast1, default: 0)
    field(:req_spell_cast2, :integer, source: :ReqSpellCast2, default: 0)
    field(:req_spell_cast3, :integer, source: :ReqSpellCast3, default: 0)
    field(:req_spell_cast4, :integer, source: :ReqSpellCast4, default: 0)
    field(:rew_choice_item_id1, :integer, source: :RewChoiceItemId1, default: 0)
    field(:rew_choice_item_id2, :integer, source: :RewChoiceItemId2, default: 0)
    field(:rew_choice_item_id3, :integer, source: :RewChoiceItemId3, default: 0)
    field(:rew_choice_item_id4, :integer, source: :RewChoiceItemId4, default: 0)
    field(:rew_choice_item_id5, :integer, source: :RewChoiceItemId5, default: 0)
    field(:rew_choice_item_id6, :integer, source: :RewChoiceItemId6, default: 0)
    field(:rew_choice_item_count1, :integer, source: :RewChoiceItemCount1, default: 0)
    field(:rew_choice_item_count2, :integer, source: :RewChoiceItemCount2, default: 0)
    field(:rew_choice_item_count3, :integer, source: :RewChoiceItemCount3, default: 0)
    field(:rew_choice_item_count4, :integer, source: :RewChoiceItemCount4, default: 0)
    field(:rew_choice_item_count5, :integer, source: :RewChoiceItemCount5, default: 0)
    field(:rew_choice_item_count6, :integer, source: :RewChoiceItemCount6, default: 0)
    field(:rew_item_id1, :integer, source: :RewItemId1, default: 0)
    field(:rew_item_id2, :integer, source: :RewItemId2, default: 0)
    field(:rew_item_id3, :integer, source: :RewItemId3, default: 0)
    field(:rew_item_id4, :integer, source: :RewItemId4, default: 0)
    field(:rew_item_count1, :integer, source: :RewItemCount1, default: 0)
    field(:rew_item_count2, :integer, source: :RewItemCount2, default: 0)
    field(:rew_item_count3, :integer, source: :RewItemCount3, default: 0)
    field(:rew_item_count4, :integer, source: :RewItemCount4, default: 0)
    field(:rew_rep_faction1, :integer, source: :RewRepFaction1, default: 0)
    field(:rew_rep_faction2, :integer, source: :RewRepFaction2, default: 0)
    field(:rew_rep_faction3, :integer, source: :RewRepFaction3, default: 0)
    field(:rew_rep_faction4, :integer, source: :RewRepFaction4, default: 0)
    field(:rew_rep_faction5, :integer, source: :RewRepFaction5, default: 0)
    field(:rew_rep_value1, :integer, source: :RewRepValue1, default: 0)
    field(:rew_rep_value2, :integer, source: :RewRepValue2, default: 0)
    field(:rew_rep_value3, :integer, source: :RewRepValue3, default: 0)
    field(:rew_rep_value4, :integer, source: :RewRepValue4, default: 0)
    field(:rew_rep_value5, :integer, source: :RewRepValue5, default: 0)
    field(:rew_or_req_money, :integer, source: :RewOrReqMoney, default: 0)
    field(:rew_money_max_level, :integer, source: :RewMoneyMaxLevel, default: 0)
    field(:rew_spell, :integer, source: :RewSpell, default: 0)
    field(:rew_spell_cast, :integer, source: :RewSpellCast, default: 0)
    field(:rew_mail_template_id, :integer, source: :RewMailTemplateId, default: 0)
    field(:rew_mail_delay_secs, :integer, source: :RewMailDelaySecs, default: 0)
    field(:point_map_id, :integer, source: :PointMapId, default: 0)
    field(:point_x, :float, source: :PointX, default: 0.0)
    field(:point_y, :float, source: :PointY, default: 0.0)
    field(:point_opt, :integer, source: :PointOpt, default: 0)
    field(:details_emote1, :integer, source: :DetailsEmote1, default: 0)
    field(:details_emote2, :integer, source: :DetailsEmote2, default: 0)
    field(:details_emote3, :integer, source: :DetailsEmote3, default: 0)
    field(:details_emote4, :integer, source: :DetailsEmote4, default: 0)
    field(:details_emote_delay1, :integer, source: :DetailsEmoteDelay1, default: 0)
    field(:details_emote_delay2, :integer, source: :DetailsEmoteDelay2, default: 0)
    field(:details_emote_delay3, :integer, source: :DetailsEmoteDelay3, default: 0)
    field(:details_emote_delay4, :integer, source: :DetailsEmoteDelay4, default: 0)
    field(:incomplete_emote, :integer, source: :IncompleteEmote, default: 0)
    field(:complete_emote, :integer, source: :CompleteEmote, default: 0)
    field(:offer_reward_emote1, :integer, source: :OfferRewardEmote1, default: 0)
    field(:offer_reward_emote2, :integer, source: :OfferRewardEmote2, default: 0)
    field(:offer_reward_emote3, :integer, source: :OfferRewardEmote3, default: 0)
    field(:offer_reward_emote4, :integer, source: :OfferRewardEmote4, default: 0)
    field(:offer_reward_emote_delay1, :integer, source: :OfferRewardEmoteDelay1, default: 0)
    field(:offer_reward_emote_delay2, :integer, source: :OfferRewardEmoteDelay2, default: 0)
    field(:offer_reward_emote_delay3, :integer, source: :OfferRewardEmoteDelay3, default: 0)
    field(:offer_reward_emote_delay4, :integer, source: :OfferRewardEmoteDelay4, default: 0)
    field(:start_script, :integer, source: :StartScript, default: 0)
    field(:complete_script, :integer, source: :CompleteScript, default: 0)

    has_many(:quest_relations, QuestRelations,
      foreign_key: :quest,
      references: :entry
    )
  end
end
