defmodule ThistleTea.Game.Core.Combat.ExtraAttacks do
  @moduledoc """
  Pending main-hand attack batches granted by spells and procs. A batch cannot
  stack with another pending batch or be generated by its own attack feedback.
  The combat behavior tree consumes it when the victim can be attacked.

  Reckoning banks single attacks instead, up to four in all, and they wait for
  the next regular swing to arm them, as vmangos's script does.
  """
  alias ThistleTea.Game.Core.AI.BT.Blackboard
  alias ThistleTea.Game.Core.AI.BT.Blackboard.Combat
  alias ThistleTea.Game.Core.Death
  alias ThistleTea.Game.Core.Entity.Component.Internal
  alias ThistleTea.Game.Core.Spell
  alias ThistleTea.Game.Core.Spell.Effect

  @held_cap 4

  def grant(%{internal: %Internal{} = internal} = entity, count, extra_attack? \\ false)
      when is_integer(count) and count > 0 do
    blackboard = Blackboard.ensure(internal.blackboard)

    if not Death.alive?(entity) or extra_attack? or banked(blackboard.combat) > 0 do
      entity
    else
      blackboard = %{blackboard | combat: %{blackboard.combat | extra_attacks: count}}
      %{entity | internal: %{internal | blackboard: blackboard}}
    end
  end

  def hold(%{internal: %Internal{} = internal} = entity) do
    blackboard = Blackboard.ensure(internal.blackboard)
    combat = blackboard.combat

    if banked(combat) < @held_cap do
      blackboard = %{blackboard | combat: %{combat | held_extra_attacks: combat.held_extra_attacks + 1}}
      %{entity | internal: %{internal | blackboard: blackboard}}
    else
      entity
    end
  end

  def arm(%Blackboard{combat: %Combat{held_extra_attacks: held} = combat} = blackboard) when held > 0 do
    %{blackboard | combat: %{combat | extra_attacks: combat.extra_attacks + held, held_extra_attacks: 0}}
  end

  def arm(%Blackboard{} = blackboard), do: blackboard

  def pending?(%{internal: %Internal{blackboard: %Blackboard{combat: %Combat{extra_attacks: count}}}}), do: count > 0
  def pending?(_entity), do: false

  def spell?(%Spell{effects: effects}), do: Enum.any?(effects, &match?(%Effect{type: :add_extra_attacks}, &1))
  def spell?(_spell), do: false

  def clear(%{internal: %Internal{} = internal} = entity) do
    blackboard = Blackboard.ensure(internal.blackboard)
    blackboard = %{blackboard | combat: %{blackboard.combat | extra_attacks: 0, held_extra_attacks: 0}}
    %{entity | internal: %{internal | blackboard: blackboard}}
  end

  defp banked(%Combat{extra_attacks: armed, held_extra_attacks: held}), do: armed + held
end
