[package]
name = "namigator_ex"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "namigator_ex"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.37.0"
once_cell = "1.19.0"
namigator = { version = "0.1.0", features = ["vanilla"] }
