#!/usr/bin/expect

spawn ./InstallDatabases.sh

expect "Please select an activity :" { sleep 1; send "n\r" }
# address
expect ": " { sleep 1; send "127.0.0.1\r" }
# user
expect ": " { sleep 1; send "root\r" }
# port
expect ": " { sleep 1; send "\r" }
# password
expect ": " { sleep 1; send "mangos\r" }
# database names
expect ": " { sleep 1; send "\r" }
expect ": " { sleep 1; send "\r" }
expect ": " { sleep 1; send "\r" }

expect eof
