defmodule ThistleTea.Game.Inbound.Dispatch do
  @moduledoc "Maps client opcodes to the inbound message modules that decode them."

  alias ThistleTea.Game.Inbound
  alias ThistleTea.Game.Network.Message
  alias ThistleTea.Game.Network.Opcodes
  alias ThistleTea.Game.Network.Packet

  @movement_opcodes [
                      :MSG_MOVE_START_FORWARD,
                      :MSG_MOVE_START_BACKWARD,
                      :MSG_MOVE_STOP,
                      :MSG_MOVE_START_STRAFE_LEFT,
                      :MSG_MOVE_START_STRAFE_RIGHT,
                      :MSG_MOVE_STOP_STRAFE,
                      :MSG_MOVE_JUMP,
                      :MSG_MOVE_START_TURN_LEFT,
                      :MSG_MOVE_START_TURN_RIGHT,
                      :MSG_MOVE_STOP_TURN,
                      :MSG_MOVE_START_PITCH_UP,
                      :MSG_MOVE_START_PITCH_DOWN,
                      :MSG_MOVE_STOP_PITCH,
                      :MSG_MOVE_SET_RUN_MODE,
                      :MSG_MOVE_SET_WALK_MODE,
                      :MSG_MOVE_FALL_LAND,
                      :MSG_MOVE_START_SWIM,
                      :MSG_MOVE_STOP_SWIM,
                      :MSG_MOVE_SET_FACING,
                      :MSG_MOVE_SET_PITCH,
                      :MSG_MOVE_HEARTBEAT,
                      :CMSG_MOVE_FALL_RESET
                    ]
                    |> Map.new(fn opcode -> {opcode, Message.MsgMove} end)

  @messages %{
              MSG_AUCTION_HELLO: Inbound.MsgAuctionHelloClient,
              CMSG_AUCTION_SELL_ITEM: Inbound.CmsgAuctionSellItem,
              CMSG_AUCTION_REMOVE_ITEM: Inbound.CmsgAuctionRemoveItem,
              CMSG_AUCTION_PLACE_BID: Inbound.CmsgAuctionPlaceBid,
              CMSG_AUCTION_LIST_ITEMS: Inbound.CmsgAuctionListItems,
              CMSG_AUCTION_LIST_OWNER_ITEMS: Inbound.CmsgAuctionListOwnerItems,
              CMSG_AUCTION_LIST_BIDDER_ITEMS: Inbound.CmsgAuctionListBidderItems,
              CMSG_INITIATE_TRADE: Inbound.CmsgInitiateTrade,
              CMSG_BEGIN_TRADE: Inbound.CmsgBeginTrade,
              CMSG_ACCEPT_TRADE: Inbound.CmsgAcceptTrade,
              CMSG_UNACCEPT_TRADE: Inbound.CmsgUnacceptTrade,
              CMSG_CANCEL_TRADE: Inbound.CmsgCancelTrade,
              CMSG_BUSY_TRADE: Inbound.CmsgBusyTrade,
              CMSG_IGNORE_TRADE: Inbound.CmsgIgnoreTrade,
              CMSG_SET_TRADE_GOLD: Inbound.CmsgSetTradeGold,
              CMSG_SET_TRADE_ITEM: Inbound.CmsgSetTradeItem,
              CMSG_CLEAR_TRADE_ITEM: Inbound.CmsgClearTradeItem,
              MSG_TALENT_WIPE_CONFIRM: Inbound.MsgTalentWipeConfirmClient,
              CMSG_AUTH_SESSION: Inbound.CmsgAuthSession,
              CMSG_CHAR_ENUM: Inbound.CmsgCharEnum,
              CMSG_CHAR_CREATE: Inbound.CmsgCharCreate,
              CMSG_CHAR_DELETE: Inbound.CmsgCharDelete,
              CMSG_GUILD_QUERY: Inbound.CmsgGuildQuery,
              CMSG_GUILD_CREATE: Inbound.CmsgGuildCreate,
              CMSG_GUILD_INVITE: Inbound.CmsgGuildInvite,
              CMSG_GUILD_ACCEPT: Inbound.CmsgGuildAccept,
              CMSG_GUILD_DECLINE: Inbound.CmsgGuildDecline,
              CMSG_GUILD_ROSTER: Inbound.CmsgGuildRoster,
              CMSG_GUILD_LEAVE: Inbound.CmsgGuildLeave,
              CMSG_GUILD_DISBAND: Inbound.CmsgGuildDisband,
              CMSG_GUILD_INFO: Inbound.CmsgGuildInfo,
              CMSG_GUILD_PROMOTE: Inbound.CmsgGuildPromote,
              CMSG_GUILD_DEMOTE: Inbound.CmsgGuildDemote,
              CMSG_GUILD_REMOVE: Inbound.CmsgGuildRemove,
              CMSG_GUILD_LEADER: Inbound.CmsgGuildLeader,
              CMSG_GUILD_MOTD: Inbound.CmsgGuildMotd,
              CMSG_GUILD_INFO_TEXT: Inbound.CmsgGuildInfoText,
              CMSG_GUILD_SET_PUBLIC_NOTE: Inbound.CmsgGuildSetPublicNote,
              CMSG_GUILD_SET_OFFICER_NOTE: Inbound.CmsgGuildSetOfficerNote,
              CMSG_GUILD_RANK: Inbound.CmsgGuildRank,
              CMSG_GUILD_ADD_RANK: Inbound.CmsgGuildAddRank,
              CMSG_GUILD_DEL_RANK: Inbound.CmsgGuildDelRank,
              MSG_TABARDVENDOR_ACTIVATE: Inbound.MsgTabardvendorActivateClient,
              MSG_SAVE_GUILD_EMBLEM: Inbound.MsgSaveGuildEmblemClient,
              CMSG_PETITION_SHOWLIST: Inbound.CmsgPetitionShowlist,
              CMSG_PETITION_BUY: Inbound.CmsgPetitionBuy,
              CMSG_PETITION_SHOW_SIGNATURES: Inbound.CmsgPetitionShowSignatures,
              CMSG_PETITION_QUERY: Inbound.CmsgPetitionQuery,
              CMSG_OFFER_PETITION: Inbound.CmsgOfferPetition,
              CMSG_PETITION_SIGN: Inbound.CmsgPetitionSign,
              CMSG_TURN_IN_PETITION: Inbound.CmsgTurnInPetition,
              MSG_PETITION_DECLINE: Inbound.MsgPetitionDeclineClient,
              MSG_PETITION_RENAME: Inbound.MsgPetitionRenameClient,
              CMSG_MESSAGECHAT: Inbound.CmsgMessagechat,
              CMSG_JOIN_CHANNEL: Inbound.CmsgJoinChannel,
              CMSG_LEAVE_CHANNEL: Inbound.CmsgLeaveChannel,
              CMSG_CHANNEL_LIST: Inbound.CmsgChannelList,
              CMSG_CHANNEL_PASSWORD: Inbound.CmsgChannelPassword,
              CMSG_CHANNEL_SET_OWNER: Inbound.CmsgChannelSetOwner,
              CMSG_CHANNEL_OWNER: Inbound.CmsgChannelOwner,
              CMSG_CHANNEL_MODERATOR: Inbound.CmsgChannelModerator,
              CMSG_CHANNEL_UNMODERATOR: Inbound.CmsgChannelUnmoderator,
              CMSG_CHANNEL_MUTE: Inbound.CmsgChannelMute,
              CMSG_CHANNEL_UNMUTE: Inbound.CmsgChannelUnmute,
              CMSG_CHANNEL_INVITE: Inbound.CmsgChannelInvite,
              CMSG_CHANNEL_KICK: Inbound.CmsgChannelKick,
              CMSG_CHANNEL_BAN: Inbound.CmsgChannelBan,
              CMSG_CHANNEL_UNBAN: Inbound.CmsgChannelUnban,
              CMSG_CHANNEL_ANNOUNCEMENTS: Inbound.CmsgChannelAnnouncements,
              CMSG_CHANNEL_MODERATE: Inbound.CmsgChannelModerate,
              CMSG_TEXT_EMOTE: Inbound.CmsgTextEmote,
              CMSG_EMOTE: Inbound.CmsgEmote,
              CMSG_PING: Inbound.CmsgPing,
              CMSG_NAME_QUERY: Inbound.CmsgNameQuery,
              CMSG_PET_NAME_QUERY: Inbound.CmsgPetNameQuery,
              CMSG_PET_RENAME: Inbound.CmsgPetRename,
              CMSG_PET_ABANDON: Inbound.CmsgPetAbandon,
              CMSG_PET_ACTION: Inbound.CmsgPetAction,
              CMSG_PET_STOP_ATTACK: Inbound.CmsgPetStopAttack,
              CMSG_PET_CANCEL_AURA: Inbound.CmsgPetCancelAura,
              CMSG_PET_CAST_SPELL: Inbound.CmsgPetCastSpell,
              CMSG_PET_UNLEARN: Inbound.CmsgPetUnlearn,
              CMSG_PET_SET_ACTION: Inbound.CmsgPetSetAction,
              CMSG_PET_SPELL_AUTOCAST: Inbound.CmsgPetSpellAutocast,
              CMSG_REQUEST_PET_INFO: Inbound.CmsgRequestPetInfo,
              MSG_LIST_STABLED_PETS: Inbound.MsgListStabledPetsClient,
              CMSG_STABLE_PET: Inbound.CmsgStablePet,
              CMSG_UNSTABLE_PET: Inbound.CmsgUnstablePet,
              CMSG_BUY_STABLE_SLOT: Inbound.CmsgBuyStableSlot,
              CMSG_STABLE_SWAP_PET: Inbound.CmsgStableSwapPet,
              CMSG_ITEM_QUERY_SINGLE: Inbound.CmsgItemQuerySingle,
              CMSG_ITEM_NAME_QUERY: Inbound.CmsgItemNameQuery,
              CMSG_READ_ITEM: Inbound.CmsgReadItem,
              CMSG_PAGE_TEXT_QUERY: Inbound.CmsgPageTextQuery,
              CMSG_GAMEOBJECT_QUERY: Inbound.CmsgGameobjectQuery,
              CMSG_CREATURE_QUERY: Inbound.CmsgCreatureQuery,
              CMSG_WHO: Inbound.CmsgWho,
              CMSG_FRIEND_LIST: Inbound.CmsgFriendList,
              CMSG_ADD_FRIEND: Inbound.CmsgAddFriend,
              CMSG_DEL_FRIEND: Inbound.CmsgDelFriend,
              CMSG_ADD_IGNORE: Inbound.CmsgAddIgnore,
              CMSG_DEL_IGNORE: Inbound.CmsgDelIgnore,
              CMSG_CHAT_IGNORED: Inbound.CmsgChatIgnored,
              CMSG_GOSSIP_HELLO: Inbound.CmsgGossipHello,
              CMSG_GOSSIP_SELECT_OPTION: Inbound.CmsgGossipSelectOption,
              CMSG_NPC_TEXT_QUERY: Inbound.CmsgNpcTextQuery,
              CMSG_ATTACKSWING: Inbound.CmsgAttackswing,
              CMSG_ATTACKSTOP: Inbound.CmsgAttackstop,
              CMSG_SETSHEATHED: Inbound.CmsgSetsheathed,
              CMSG_SET_SELECTION: Inbound.CmsgSetSelection,
              CMSG_SET_ACTION_BUTTON: Inbound.CmsgSetActionButton,
              CMSG_SET_ACTIONBAR_TOGGLES: Inbound.CmsgSetActionbarToggles,
              CMSG_SET_FACTION_ATWAR: Inbound.CmsgSetFactionAtwar,
              CMSG_SET_FACTION_INACTIVE: Inbound.CmsgSetFactionInactive,
              CMSG_SET_WATCHED_FACTION: Inbound.CmsgSetWatchedFaction,
              CMSG_STANDSTATECHANGE: Inbound.CmsgStandstatechange,
              CMSG_ZONEUPDATE: Inbound.CmsgZoneupdate,
              CMSG_AREATRIGGER: Inbound.CmsgAreatrigger,
              CMSG_BATTLEMASTER_HELLO: Inbound.CmsgBattlemasterHello,
              CMSG_BATTLEMASTER_JOIN: Inbound.CmsgBattlemasterJoin,
              CMSG_BATTLEFIELD_LIST: Inbound.CmsgBattlefieldList,
              CMSG_BATTLEFIELD_JOIN: Inbound.CmsgBattlefieldJoin,
              CMSG_BATTLEFIELD_STATUS: Inbound.CmsgBattlefieldStatus,
              CMSG_BATTLEFIELD_PORT: Inbound.CmsgBattlefieldPort,
              CMSG_LEAVE_BATTLEFIELD: Inbound.CmsgLeaveBattlefield,
              CMSG_AREA_SPIRIT_HEALER_QUERY: Inbound.CmsgAreaSpiritHealerQuery,
              CMSG_AREA_SPIRIT_HEALER_QUEUE: Inbound.CmsgAreaSpiritHealerQueue,
              MSG_PVP_LOG_DATA: Inbound.CmsgPvpLogData,
              MSG_INSPECT_HONOR_STATS: Inbound.CmsgInspectHonorStats,
              CMSG_INSPECT: Inbound.CmsgInspect,
              CMSG_TOGGLE_PVP: Inbound.CmsgTogglePvp,
              MSG_BATTLEGROUND_PLAYER_POSITIONS: Inbound.CmsgBattlegroundPlayerPositions,
              CMSG_CAST_SPELL: Inbound.CmsgCastSpell,
              CMSG_MEETINGSTONE_JOIN: Inbound.CmsgMeetingstoneJoin,
              CMSG_MEETINGSTONE_LEAVE: Inbound.CmsgMeetingstoneLeave,
              CMSG_MEETINGSTONE_INFO: Inbound.CmsgMeetingstoneInfo,
              CMSG_PLAYER_LOGIN: Inbound.CmsgPlayerLogin,
              CMSG_SET_ACTIVE_MOVER: Inbound.CmsgSetActiveMover,
              CMSG_MOVE_NOT_ACTIVE_MOVER: Inbound.CmsgMoveNotActiveMover,
              CMSG_FAR_SIGHT: Inbound.CmsgFarSight,
              MSG_MOVE_WORLDPORT_ACK: Inbound.CmsgMoveWorldportAck,
              CMSG_FORCE_RUN_SPEED_CHANGE_ACK: Inbound.CmsgForceRunSpeedChangeAck,
              CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK: Inbound.CmsgForceRunBackSpeedChangeAck,
              CMSG_FORCE_SWIM_SPEED_CHANGE_ACK: Inbound.CmsgForceSwimSpeedChangeAck,
              CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK: Inbound.CmsgForceSwimBackSpeedChangeAck,
              CMSG_FORCE_MOVE_ROOT_ACK: Inbound.CmsgForceMoveRootAck,
              CMSG_MOVE_FEATHER_FALL_ACK: Inbound.CmsgMoveFeatherFallAck,
              CMSG_MOVE_WATER_WALK_ACK: Inbound.CmsgMoveWaterWalkAck,
              CMSG_MOVE_KNOCK_BACK_ACK: Inbound.CmsgMoveKnockBackAck,
              CMSG_FORCE_MOVE_UNROOT_ACK: Inbound.CmsgForceMoveUnrootAck,
              CMSG_MOVE_TIME_SKIPPED: Inbound.CmsgMoveTimeSkipped,
              CMSG_MOVE_SPLINE_DONE: Inbound.CmsgMoveSplineDone,
              CMSG_LOGOUT_REQUEST: Inbound.CmsgLogoutRequest,
              CMSG_LOGOUT_CANCEL: Inbound.CmsgLogoutCancel,
              CMSG_CANCEL_CAST: Inbound.CmsgCancelCast,
              CMSG_CANCEL_CHANNELLING: Inbound.CmsgCancelChannelling,
              CMSG_CANCEL_AUTO_REPEAT_SPELL: Inbound.CmsgCancelAutoRepeatSpell,
              CMSG_CANCEL_AURA: Inbound.CmsgCancelAura,
              CMSG_CANCEL_GROWTH_AURA: Inbound.CmsgCancelGrowthAura,
              CMSG_SUMMON_RESPONSE: Inbound.CmsgSummonResponse,
              CMSG_AUTOEQUIP_ITEM: Inbound.CmsgAutoequipItem,
              CMSG_AUTOEQUIP_ITEM_SLOT: Inbound.CmsgAutoequipItemSlot,
              CMSG_SWAP_INV_ITEM: Inbound.CmsgSwapInvItem,
              CMSG_SWAP_ITEM: Inbound.CmsgSwapItem,
              CMSG_SPLIT_ITEM: Inbound.CmsgSplitItem,
              CMSG_DESTROYITEM: Inbound.CmsgDestroyitem,
              CMSG_SET_AMMO: Inbound.CmsgSetAmmo,
              CMSG_BANKER_ACTIVATE: Inbound.CmsgBankerActivate,
              CMSG_BINDER_ACTIVATE: Inbound.CmsgBinderActivate,
              CMSG_BUY_BANK_SLOT: Inbound.CmsgBuyBankSlot,
              CMSG_REPAIR_ITEM: Inbound.CmsgRepairItem,
              CMSG_AUTOBANK_ITEM: Inbound.CmsgAutobankItem,
              CMSG_AUTOSTORE_BANK_ITEM: Inbound.CmsgAutostoreBankItem,
              CMSG_AUTOSTORE_BAG_ITEM: Inbound.CmsgAutostoreBagItem,
              CMSG_USE_ITEM: Inbound.CmsgUseItem,
              CMSG_OPEN_ITEM: Inbound.CmsgOpenItem,
              CMSG_WRAP_ITEM: Inbound.CmsgWrapItem,
              CMSG_LIST_INVENTORY: Inbound.CmsgListInventory,
              CMSG_BUY_ITEM: Inbound.CmsgBuyItem,
              CMSG_BUY_ITEM_IN_SLOT: Inbound.CmsgBuyItemInSlot,
              CMSG_SELL_ITEM: Inbound.CmsgSellItem,
              CMSG_BUYBACK_ITEM: Inbound.CmsgBuybackItem,
              CMSG_LOOT: Inbound.CmsgLoot,
              CMSG_AUTOSTORE_LOOT_ITEM: Inbound.CmsgAutostoreLootItem,
              CMSG_LOOT_MONEY: Inbound.CmsgLootMoney,
              CMSG_LOOT_RELEASE: Inbound.CmsgLootRelease,
              CMSG_QUESTGIVER_STATUS_QUERY: Inbound.CmsgQuestgiverStatusQuery,
              CMSG_QUEST_QUERY: Inbound.CmsgQuestQuery,
              CMSG_QUERY_TIME: Inbound.CmsgQueryTime,
              CMSG_PLAYED_TIME: Inbound.CmsgPlayedTime,
              CMSG_TOGGLE_HELM: Inbound.CmsgToggleHelm,
              CMSG_TOGGLE_CLOAK: Inbound.CmsgToggleCloak,
              CMSG_TUTORIAL_FLAG: Inbound.CmsgTutorialFlag,
              CMSG_UPDATE_ACCOUNT_DATA: Inbound.CmsgUpdateAccountData,
              CMSG_REQUEST_ACCOUNT_DATA: Inbound.CmsgRequestAccountData,
              CMSG_TUTORIAL_CLEAR: Inbound.CmsgTutorialClear,
              CMSG_TUTORIAL_RESET: Inbound.CmsgTutorialReset,
              CMSG_NEXT_CINEMATIC_CAMERA: Inbound.CmsgNextCinematicCamera,
              CMSG_COMPLETE_CINEMATIC: Inbound.CmsgCompleteCinematic,
              CMSG_QUESTGIVER_HELLO: Inbound.CmsgQuestgiverHello,
              CMSG_QUESTGIVER_QUERY_QUEST: Inbound.CmsgQuestgiverQueryQuest,
              CMSG_QUESTGIVER_ACCEPT_QUEST: Inbound.CmsgQuestgiverAcceptQuest,
              CMSG_QUESTGIVER_CANCEL: Inbound.CmsgQuestgiverCancel,
              CMSG_QUESTLOG_REMOVE_QUEST: Inbound.CmsgQuestlogRemoveQuest,
              CMSG_PUSHQUESTTOPARTY: Inbound.CmsgPushquesttoparty,
              CMSG_QUEST_CONFIRM_ACCEPT: Inbound.CmsgQuestConfirmAccept,
              MSG_QUEST_PUSH_RESULT: Inbound.MsgQuestPushResultClient,
              CMSG_QUESTGIVER_COMPLETE_QUEST: Inbound.CmsgQuestgiverCompleteQuest,
              CMSG_QUESTGIVER_REQUEST_REWARD: Inbound.CmsgQuestgiverRequestReward,
              CMSG_QUESTGIVER_CHOOSE_REWARD: Inbound.CmsgQuestgiverChooseReward,
              CMSG_TRAINER_LIST: Inbound.CmsgTrainerList,
              CMSG_UNLEARN_SKILL: Inbound.CmsgUnlearnSkill,
              CMSG_TRAINER_BUY_SPELL: Inbound.CmsgTrainerBuySpell,
              CMSG_TAXINODE_STATUS_QUERY: Inbound.CmsgTaxinodeStatusQuery,
              CMSG_TAXIQUERYAVAILABLENODES: Inbound.CmsgTaxiqueryavailablenodes,
              CMSG_ACTIVATETAXI: Inbound.CmsgActivatetaxi,
              CMSG_ACTIVATETAXIEXPRESS: Inbound.CmsgActivatetaxiexpress,
              CMSG_LEARN_TALENT: Inbound.CmsgLearnTalent,
              CMSG_REPOP_REQUEST: Inbound.CmsgRepopRequest,
              MSG_MOVE_TELEPORT_ACK: Inbound.CmsgMoveTeleportAck,
              MSG_CORPSE_QUERY: Inbound.MsgCorpseQuery,
              CMSG_RECLAIM_CORPSE: Inbound.CmsgReclaimCorpse,
              CMSG_SPIRIT_HEALER_ACTIVATE: Inbound.CmsgSpiritHealerActivate,
              CMSG_RESURRECT_RESPONSE: Inbound.CmsgResurrectResponse,
              CMSG_SELF_RES: Inbound.CmsgSelfRes,
              CMSG_GAMEOBJ_USE: Inbound.CmsgGameobjUse,
              CMSG_GROUP_INVITE: Inbound.CmsgGroupInvite,
              CMSG_GROUP_ACCEPT: Inbound.CmsgGroupAccept,
              CMSG_GROUP_DECLINE: Inbound.CmsgGroupDecline,
              CMSG_GROUP_UNINVITE: Inbound.CmsgGroupUninvite,
              CMSG_GROUP_UNINVITE_GUID: Inbound.CmsgGroupUninviteGuid,
              CMSG_GROUP_SET_LEADER: Inbound.CmsgGroupSetLeader,
              CMSG_GROUP_DISBAND: Inbound.CmsgGroupDisband,
              CMSG_GROUP_RAID_CONVERT: Inbound.CmsgGroupRaidConvert,
              CMSG_GROUP_CHANGE_SUB_GROUP: Inbound.CmsgGroupChangeSubGroup,
              CMSG_GROUP_SWAP_SUB_GROUP: Inbound.CmsgGroupSwapSubGroup,
              CMSG_GROUP_ASSISTANT_LEADER: Inbound.CmsgGroupAssistantLeader,
              MSG_RAID_TARGET_UPDATE: Inbound.MsgRaidTargetUpdate,
              MSG_RAID_READY_CHECK: Inbound.MsgRaidReadyCheck,
              CMSG_LOOT_METHOD: Inbound.CmsgLootMethod,
              CMSG_LOOT_ROLL: Inbound.CmsgLootRoll,
              CMSG_LOOT_MASTER_GIVE: Inbound.CmsgLootMasterGive,
              CMSG_REQUEST_PARTY_MEMBER_STATS: Inbound.CmsgRequestPartyMemberStats,
              CMSG_RESET_INSTANCES: Inbound.CmsgResetInstances,
              CMSG_REQUEST_RAID_INFO: Inbound.CmsgRequestRaidInfo,
              CMSG_DUEL_ACCEPTED: Inbound.CmsgDuelAccepted,
              CMSG_DUEL_CANCELLED: Inbound.CmsgDuelCancelled,
              CMSG_SEND_MAIL: Inbound.CmsgSendMail,
              CMSG_GET_MAIL_LIST: Inbound.CmsgGetMailList,
              CMSG_MAIL_TAKE_MONEY: Inbound.CmsgMailTakeMoney,
              CMSG_MAIL_TAKE_ITEM: Inbound.CmsgMailTakeItem,
              CMSG_MAIL_MARK_AS_READ: Inbound.CmsgMailMarkAsRead,
              CMSG_MAIL_RETURN_TO_SENDER: Inbound.CmsgMailReturnToSender,
              CMSG_MAIL_DELETE: Inbound.CmsgMailDelete,
              CMSG_ITEM_TEXT_QUERY: Inbound.CmsgItemTextQuery,
              CMSG_MAIL_CREATE_TEXT_ITEM: Inbound.CmsgMailCreateTextItem,
              MSG_QUERY_NEXT_MAIL_TIME: Inbound.MsgQueryNextMailTimeClient,
              MSG_MINIMAP_PING: Inbound.MsgMinimapPing,
              MSG_RANDOM_ROLL: Inbound.MsgRandomRoll
            }
            |> Map.merge(@movement_opcodes)
            |> Map.new(fn {opcode, module} -> {Opcodes.get(opcode), module} end)

  def to_message(%Packet{opcode: opcode, payload: payload}) do
    module = Map.fetch!(@messages, opcode)

    payload
    |> module.from_binary()
    |> struct(opcode: opcode)
  end

  def messages, do: @messages |> Map.values() |> Enum.uniq()

  def implemented?(opcode) when is_number(opcode) do
    Map.has_key?(@messages, opcode)
  end
end
