defmodule ThistleTea.Game.Entity.Logic.ExtraAttacks do
  @moduledoc """
  Pending main-hand attack batches granted by spells and procs. A batch cannot
  stack with another pending batch or be generated by its own attack feedback.
  The combat behavior tree consumes it when the victim can be attacked.
  """
  alias ThistleTea.Game.Entity.Data.Component.Internal
  alias ThistleTea.Game.Entity.Logic.AI.BT.Blackboard
  alias ThistleTea.Game.Entity.Logic.AI.BT.Blackboard.Combat
  alias ThistleTea.Game.Entity.Logic.Death
  alias ThistleTea.Game.Spell
  alias ThistleTea.Game.Spell.Effect

  def grant(%{internal: %Internal{} = internal} = entity, count, extra_attack? \\ false)
      when is_integer(count) and count > 0 do
    blackboard = Blackboard.ensure(internal.blackboard)

    if not Death.alive?(entity) or extra_attack? or blackboard.combat.extra_attacks > 0 do
      entity
    else
      blackboard = %{blackboard | combat: %{blackboard.combat | extra_attacks: count}}
      %{entity | internal: %{internal | blackboard: blackboard}}
    end
  end

  def pending?(%{internal: %Internal{blackboard: %Blackboard{combat: %Combat{extra_attacks: count}}}}), do: count > 0
  def pending?(_entity), do: false

  def spell?(%Spell{effects: effects}), do: Enum.any?(effects, &match?(%Effect{type: :add_extra_attacks}, &1))
  def spell?(_spell), do: false

  def clear(%{internal: %Internal{} = internal} = entity) do
    blackboard = Blackboard.ensure(internal.blackboard)
    blackboard = %{blackboard | combat: %{blackboard.combat | extra_attacks: 0}}
    %{entity | internal: %{internal | blackboard: blackboard}}
  end
end
